### ISSUE TITLE
immediately discarded

### ISSUE THREAD

**Issue by martijnr17** [tpaksu/laravel-otp-login#2]
After a login the otp code is immediately discarded instead of waiting. So I'm in an constant loop. I'm using laravel 5.8

**Comment by tpaksu** [comment]
Hi @martijnr17, If you logout using the logout button, the code will be discarded yes. What do you want the code to act like?

**Comment by martijnr17** [comment]
I didn't press the logout button, only login and the code is discarded instead of waiting. Because that wasn't working i'm using another plugin at the moment.

**Comment by tpaksu** [comment]
Ok, thanks for the information. I should add more debug codes to show what's wrong on development side.
