### ISSUE TITLE
Unable to implement

### ISSUE THREAD

**Issue by bhagchandani** [tpaksu/laravel-otp-login#5]
I follow the instructions, also created the phone field in the user's table. but there was no instruction on how can I use it.
Please let me know should I change the route or instead of an email I use the phone field. 

Thanks in advance.

**Comment by tpaksu** [comment]
Hello, you don't need to change anything, the library adds the middleware to the login routes automatically. Did you change the default login and logout routes in your configuration? Did you add the required keys to your .env file? I can't understand your problem with little details you've given.

**Comment by bhagchandani** [comment]
Yes, I have changed the default auth routes. Maybe tha is why it was not working for me.

**Comment by tpaksu** [comment]
You need to check if the middleware works first. Open `/vendor/tpaksu/laravel-otp-login/src/LoginMiddleware.php` file and set the `$debug` variable to true. Then try to log in and see your error logs if any debug lines are logged.

https://github.com/tpaksu/laravel-otp-login/blob/7d27485a410fa8273d24c58f7e35af7faf9cc316/src/LoginMiddleware.php#L11-L16

**Comment by bhagchandani** [comment]
The package seems working fine on a fresh setup and in my project basic routes has been modified. i need to implement the process differently. I will be closeing the issue. Thanks for your support.
