### ISSUE TITLE
Model Change

### ISSUE THREAD

**Issue by sharjeelz** [tpaksu/laravel-otp-login#6]
Hi is there a way to change the model from user to lets say admins table? I am maintainng the admin login users in seperate table, and I added Admin model and default in auth.php

**Comment by sharjeelz** [comment]
@tpaksu  please help

**Comment by tpaksu** [comment]
Hey! You can fork the repo and change the model as you wish. It's using the model that Auth::user() returns and in some places, the user model is type hinted. You'll need to change them too.

**Comment by usamaJ17** [comment]
Hi, you have hard coted the primary key of user column. I am using _id as primary key. I have to change it every where. How to tackle with this. If I update this pkge all my modification would be gone.

**Comment by usamaJ17** [comment]
@tpaksu
