### ISSUE TITLE
different primary key for user table

### ISSUE THREAD

**Issue by usamaJ17** [tpaksu/laravel-otp-login#7]
Hi @tpaksu , you have hard coted the primary key of user column. I am using _id as primary key. I have to change it every where. How to tackle with this. If I update this pkge all my modification would be gone.

**Comment by tpaksu** [comment]
Hi @usamaJ17, I think you can fork it, and modify it to suit your needs, then register your package to the npm repository, to use your copy. It's the final version of the plugin, I don't work on this anymore. Sorry.

**Comment by tpaksu** [comment]
Or you can create a PR that lets people specify primary key columns from config file, and I'll review and merge it.

**Comment by usamaJ17** [comment]
thanks.. will try

**Comment by tpaksu** [comment]
Thank you!

**Comment by usamaJ17** [comment]
hi, @tpaksu , I created a pull request 😊
